<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <UseWPF>true</UseWPF>
    <ApplicationIcon>MicroSign.ico</ApplicationIcon>
    <AssemblyTitle>MicroSignアニメーション作成</AssemblyTitle>
    <ApplicationManifest>app.manifest</ApplicationManifest>
    <PlatformTarget>AnyCPU</PlatformTarget>
    <SelfContained>true</SelfContained>
    <RuntimeIdentifier>win-x64</RuntimeIdentifier>
    <Platforms>AnyCPU;x64</Platforms>
  </PropertyGroup>

  <ItemGroup>
    <Resource Include="MicroSign.ico" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="log4net" Version="3.3.1" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\MicroSign.Core\MicroSign.Core\MicroSign.Core.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Prms\" />
  </ItemGroup>

  <ItemGroup>
    <None Update="Prms\log4net.xml">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
  </ItemGroup>

</Project>
  