<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0-windows</TargetFramework>
    <ImplicitUsings>disable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <UseWPF>true</UseWPF>
    <AssemblyTitle>MicroSignアニメーション作成 コア</AssemblyTitle>
    <PlatformTarget>AnyCPU</PlatformTarget>
    <Platforms>AnyCPU;x64</Platforms>
  </PropertyGroup>

  <ItemGroup>
    <None Remove="IconImages\Confirm.png" />
    <None Remove="IconImages\Error.png" />
    <None Remove="IconImages\Info.png" />
    <None Remove="IconImages\Warning.png" />
  </ItemGroup>

  <ItemGroup>
    <Resource Include="IconImages\Error.png" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="CeresSoft.MediaFoundation" Version="3.1.3" />
    <PackageReference Include="CeresSoft.MediaFoundation.Extension" Version="3.1.3" />
    <PackageReference Include="Magick.NET-Q8-AnyCPU" Version="14.14.0" />
    <PackageReference Include="Magick.NET.SystemWindowsMedia" Version="8.0.22" />
    <PackageReference Include="Microsoft.Xaml.Behaviors.Wpf" Version="1.1.77" />
    <PackageReference Include="NAudio" Version="2.3.0" />
  </ItemGroup>

  <ItemGroup>
    <Resource Include="IconImages\Confirm.png" />
    <Resource Include="IconImages\Info.png" />
    <Resource Include="IconImages\Warning.png" />
  </ItemGroup>

</Project>
